# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from urllib3._collections import HTTPHeaderDict

from aitrios_console_rest_client_sdk_primitive import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from aitrios_console_rest_client_sdk_primitive import schemas  # noqa: F401

from aitrios_console_rest_client_sdk_primitive.model.error_response import ErrorResponse

# query params
ConfigIdSchema = schemas.StrSchema
CommentSchema = schemas.StrSchema
DeviceTypeSchema = schemas.StrSchema
SensorLoaderVersionNumberSchema = schemas.StrSchema
SensorVersionNumberSchema = schemas.StrSchema
ModelIdSchema = schemas.StrSchema
ModelVersionNumberSchema = schemas.StrSchema
ColorMatrixModeSchema = schemas.StrSchema
ColorMatrixFileNameSchema = schemas.StrSchema
GammaModeSchema = schemas.StrSchema
GammaFileNameSchema = schemas.StrSchema
LscispModeSchema = schemas.StrSchema
LscispFileNameSchema = schemas.StrSchema
LscrawModeSchema = schemas.StrSchema
LscrawFileNameSchema = schemas.StrSchema
PrewbModeSchema = schemas.StrSchema
PrewbFileNameSchema = schemas.StrSchema
DewarpModeSchema = schemas.StrSchema
DewarpFileNameSchema = schemas.StrSchema
ApFwVersionNumberSchema = schemas.StrSchema
SchemaFor200ResponseBodyApplicationJson = schemas.AnyTypeSchema
SchemaFor400ResponseBodyApplicationJson = ErrorResponse
SchemaFor401ResponseBodyApplicationJson = ErrorResponse
SchemaFor403ResponseBodyApplicationJson = ErrorResponse
SchemaFor500ResponseBodyApplicationJson = ErrorResponse
SchemaFor503ResponseBodyApplicationJson = ErrorResponse
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _create_deploy_configuration_oapg(
        self: api_client.Api,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization
    ]:
        """
        CreateDeployConfiguration
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value

        prefix_separator_iterator = None
        for parameter in (
            request_query_config_id,
            request_query_comment,
            request_query_device_type,
            request_query_sensor_loader_version_number,
            request_query_sensor_version_number,
            request_query_model_id,
            request_query_model_version_number,
            request_query_color_matrix_mode,
            request_query_color_matrix_file_name,
            request_query_gamma_mode,
            request_query_gamma_file_name,
            request_query_lscisp_mode,
            request_query_lscisp_file_name,
            request_query_lscraw_mode,
            request_query_lscraw_file_name,
            request_query_prewb_mode,
            request_query_prewb_file_name,
            request_query_dewarp_mode,
            request_query_dewarp_file_name,
            request_query_ap_fw_version_number,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value

        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)

        response = self.api_client.call_api(
            resource_path=used_path,
            method='post'.upper(),
            headers=_headers,
            stream=stream,
            timeout=timeout,
        )

        if skip_deserialization:
            api_response = api_client.ApiResponseWithoutDeserialization(response=response)
        else:
            response_for_status = _status_code_to_response.get(str(response.status))
            if response_for_status:
                api_response = response_for_status.deserialize(response, self.api_client.configuration)
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(response=response)

        if not 200 <= response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)

        return api_response


class CreateDeployConfiguration(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    def create_deploy_configuration(
        self: BaseApi,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization
    ]:
        return self._create_deploy_configuration_oapg(
            query_params=query_params,
            accept_content_types=accept_content_types,
            stream=stream,
            timeout=timeout,
            skip_deserialization=skip_deserialization
        )


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    def post(
        self: BaseApi,
        query_params: RequestQueryParams = frozendict.frozendict(),
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization
    ]:
        return self._create_deploy_configuration_oapg(
            query_params=query_params,
            accept_content_types=accept_content_types,
            stream=stream,
            timeout=timeout,
            skip_deserialization=skip_deserialization
        )


