= Cloud SDK pass:[<br/>] Console Access Library pass:[<br/>] Python版 pass:[<br/>] チュートリアル pass:[<br/>]
:sectnums:
:sectnumlevels: 1
:author: Copyright 2023 Sony Semiconductor Solutions Corporation
:version-label: Version 
:revnumber: x.x.x
:revdate: YYYY - MM - DD
:trademark-desc: AITRIOS™、およびそのロゴは、ソニーグループ株式会社またはその関連会社の登録商標または商標です。
:toc:
:toc-title: 目次
:toclevels: 1
:chapter-label:
:lang: ja

== 目的

このチュートリアルでは「**Console Access Library**」が公開する各種APIについて解説します。本書を通じてLibraryをビルドして使用できるようになります。

== 前提条件
- Python 3.11.8
- Python依存関係

    * requests>=2.31.0
    * jsonschema>=4.6.2
    * setuptools>=65.5.1
    * wheel>=0.37.1
    * PyYAML>=6.0
    * marshmallow>=3.17.0
    * pytest>=7.1.2
    * pytest-html-reporter>=0.2.9
    * pytest-ordering>=0.6
    * sphinx==4.3.2
    * myst-parser>=0.18.0
    * sphinx-rtd-theme>=1.0.0
    * sphinxcontrib-napoleon>=0.7
    * rst2pdf>=0.99
    * streamlit==1.11.1
    * pytest-timeout>=2.1.0
    * PyJWT>=2.6.0
    * nassl>=4.0
    * cryptography>=36.0
    * validators>=0.18
    * msal>=1.22.0

[[api-specifications]]
=== 「**Console Access Library**」 API仕様
「**Console Access Library**」のAPI仕様を参照する方法は、下記の手順を参照してください。

1. リポジトリをクローンします
    ** https://github.com/SonySemiconductorSolutions/aitrios-sdk-console-access-lib-python

2. クローンしたディレクトリ内に存在する `**docs/api-reference/index.html**` をウェブブラウザで開きます。

== 使用法

=== インストール

. リポジトリをクローンします。
    ** https://github.com/SonySemiconductorSolutions/aitrios-sdk-console-access-lib-python

. デモアプリケーション用にPython依存関係をインストールします。
+
```
    pip install -r requirements.txt
```

. 次のコマンドを実行してPython環境へのインストールを行います。
+
```
    python -m pip install lib/python-client/.
```

. 次のコマンドを実行してPython環境へのインストールを行います。
+
```
    python -m pip install src/.
```

. ネットワークProxy設定
+
プロキシ環境で「**Console Access Library**」を使用するには `**https_proxy**` 環境変数を設定します。
+
```
    export https_proxy=http://username:password@proxyhost:port
```

<<<

=== 「**Console Access Library**」サンプルアプリケーション開始用のパラメータ設定

1.  Console Access設定ファイルを作成してユーザー環境値を入力します。 + 
作成したファイルは `**console_access_settings.yaml**` のファイル名で `**samples**` 配下に配置します。 

+ 
`samples/console_access_settings.yaml`
+

|===
|「**Console Developer Edition**」を使用する場合
a|
[source,Yaml]
----
    console_access_settings:
        console_endpoint: "__console_endpoint__"
        portal_authorization_endpoint: "__portal_authorization_endpoint__"
        client_secret: "__client_secret__"
        client_id: "__client_id__"
----
|===

+

|===
|「**Console Enterprise Edition**」を使用する場合
a|
[source,Yaml]
----
    console_access_settings:
        console_endpoint: "__base_url__"
        portal_authorization_endpoint: "https://login.microsoftonline.com/'__tenant_id__'"
        client_secret: "__creant_secret__"
        client_id: "__client_id__"
        application_id: "__application_id__"
----
|===
+ 
環境変数からエクスポート場合は、下記のコマンドでユーザー環境値を環境変数に設定します。 +
その場合は、 `**console_access_settings.yaml**` の設定ファイルの作成は不要です。
+ 
```
    export CONSOLE_ENDPOINT="__console_endpoint__"
    export PORTAL_AUTHORIZATION_ENDPOINT="__portal_authorization_endpoint__"
    export CLIENT_SECRET="__client_secret__"
    export CLIENT_ID="__client_id__"
    export APPLICATION_ID="__application_id__"    #「Console Enterprise Edition」使用時のみ設定
```

2. ユーザー側で用意したApplicationのwasmファイルまたはaotファイルを `**samples**` 配下に配置します。

3. 下記のファイルを開きパラメータを適切な値に変更します。

+ 
`samples/demo_config.yaml`
+
|===
|必須パラメータのみ設定する場合
a|
----
demo_configuration:
   device_id: "__device_id__"
   model_id: "__model_id__"
   model: "__model__"
   config_id: "__config_id__"
   app_name: "__app_name__"
   file_content_name: "__file_content_name__"
   version_number: "__version_number__"
   sub_directory_name: "__sub_directory_name__"
----
|===
+
    ** `**device_id**` にデバイスIDを指定してください。
    ** `**model_id**` に「**Console**」に登録する任意のモデルの名前を指定してください。
    ** `**model**` にモデルファイルのSAS URIまたは署名付きURIを指定してください。
    ** `**config_id**` に「**Console**」に登録する任意のConfigの名前を指定してください。
    ** `**app_name**` に「**Console**」に登録する任意のApplicationの名前を指定してください。
    ** `**file_content_name**` に2.で配置したwasmファイルまたはaotファイルのファイル名を指定してください。
    ** `**version_number**` に「**Console**」に登録する任意のApplicationのバージョンを指定してください。
    ** `**sub_directory_name**` にエッジデバイスの任意のサブディレクトリを指定してください。
+
NOTE: `**model_id**` 、`**config_id**` 、`**app_name**` は既に「**Console**」に登録されているものと重複しない値を指定してください。
+
|===
|オプションのパラメータをすべて含んで設定する場合
a|
----
demo_configuration:
   device_id: "__device_id__"
   get_model_device_id: "__get_model_device_id__"
   publish_model_wait_response_device_id: "__publish_model_wait_response_device_id__"
   model_id: "__model_id__"
   model: "__model__"
   converted: "__converted__"
   vendor_name: "__vendor_name__"
   comment: "__comment__"
   input_format_param: "__input_format_param__"
   network_config: "__network_config__"
   network_type: "__network_type__"
   metadata_format_id: "__metadata_format_id__"
   project_name: "__project_name__"
   model_platform: "__model_platform__"
   project_type: "__project_type__"
   latest_type: "__latest_type__"
   config_id: "__config_id__"
   sensor_loader_version_number: "__sensor_loader_version_number__"
   sensor_version_number: "__sensor_version_number__"
   model_version_number: "__model_version_number__"
   ap_fw_version_number: "__ap_fw_version_number__"
   device_ids: "__device_ids__"
   replace_model_id: "__replace_model_id__"
   timeout: "__timeout__"
   app_name: "__app_name__"
   file_content_name: "__file_content_name__"
   version_number: "__version_number__"
   file_name: "__file_name__"
   entry_point: "__entry_point__"
   schema_info: "__schema_info__"
   device_name: "__device_name__"
   connection_state: "__connection_state__"
   device_group_id: "__device_group_id__"
   scope: "__scope__"
   sub_directory_name: "__sub_directory_name__"
   number_of_images: "__number_of_images__"
   skip: "__skip__"
   order_by: "__order_by__"
   number_of_inference_results: "__number_of_inference_results__"
   filter: "__filter__"
   raw: "__raw__"
   time: "__time__"
----
|===
オプションのパラメータの詳細については、<<api-specifications,「**Console Access Library**」 API仕様>>を参照してください。

=== アプリケーション開始

CLIデモを実行するにはrootフォルダからcmdターミナルを開き、次のコマンドを実行します。

```
    python samples/console_access_client_api_demo.py
```

NOTE: demo-consoleでAPIを一括実行した場合は、他のAPIの処理時間の影響により失敗することがあります。 +
その場合は失敗したAPIを個別で実行してください。
APIを個別で実行する場合は、samples/console_access_client_api_demo.pyを開き、実行しないAPIをコメントアウトしてください。  

* 例：
|===
|samples/console_access_client_api_demo.py
a|
----
    # DeviceManagement - StartUploadInferenceResult
    # response = device_management_obj.start_upload_inference_result(device_id=device_id)
    # print("START UPLOAD INFERENCE RESULT:", response)
----
|===


== 「**Console Access Library**」の使用方法
1. 「**Console Access Library**」から `**Client**` と `**Config**` のクラスをインポートします。
+
[source,Python]
----
    from console_access_library.client import Client
    from console_access_library.common.config import Config
----

2. `**Config**` に接続情報を引数として渡し、 `**Config**` インスタンスを生成します。 +
`**Config**` インスタンスを `**Client**` コンストラクタの引数として渡し、 `**Client**` インスタンスを生成します。
+
[source,Python]
----
    config_obj = Config(
            console_endpoint,
            portal_authorization_endpoint,
            client_id,
            client_secret,
            application_id    #「Console Enterprise Edition」使用時のみ指定
        )
    client_obj = Client(config_obj)
----

3. `**Client**` インスタンスのインスタンス変数が持つ任意のAPIを呼び出します。
+
[source,Python]
----
    client_obj.device_management.get_command_parameter_file()
----