= Cloud SDK pass:[<br/>] Console Access Library pass:[<br/>] Python版 pass:[<br/>] 機能仕様書 pass:[<br/>]
:sectnums:
:sectnumlevels: 1
:author: Copyright 2023 Sony Semiconductor Solutions Corporation
:version-label: Version 
:revnumber: x.x.x
:revdate: YYYY - MM - DD
:trademark-desc: AITRIOS™、およびそのロゴは、ソニーグループ株式会社またはその関連会社の登録商標または商標です。
:toc:
:toc-title: 目次
:toclevels: 1
:chapter-label:
:lang: ja

== 更新履歴

|===
|Date |What/Why 
|2022/11/16
|初版作成

|2023/1/30
|version 0.2.0 修正対応 +
表現統一 + 
PDFビルド環境更新

|2023/5/26
|version 1.0.0 修正対応

|===

== はじめに

* 本書は、「**Console**」へのアクセスを提供する「**Console Access Library**」についての機能仕様である。 + 
機能開発言語には、Pythonを使用する。

== 用語・略語
|===
|Terms/Abbreviations |Meaning 

|「**Console for AITRIOS**」
|エッジからクラウドを含めたソリューションを効率的に導入するための各種機能（デプロイメント機能、リトレーニング機能、エッジAIデバイスマネジメント機能など）を提供するクラウドサービス +
以降、本文中では「**Console**」と記載する

|「**Low Level SDK**」
|「**Console REST API**」のAPI仕様（yaml）からOpenAPI Generatorで自動生成したClient

|「**Cloud App**」
|「**Console Access Library**」を使用するアプリケーション

|SAS
|Shared Access Signatures +
Azure Storage リソースへの制限付きアクセス権を付与する URI

|
|

|===

== 想定ユースケース
* 「**Console Access Library**」を使用して、下記を実施する
** エッジAIデバイスの情報を取得
** エッジAIデバイスに推論開始（推論結果アップロード開始）、推論停止（推論結果アップロード停止）
** エッジAIデバイスの出力結果（画像、推論結果）の取得
** ユーザーが自分で作成したAI Modelを「**Console**」にアップロード
*** アップロードしたAI Modelの確認と削除
** AI ModelをエッジAIデバイスにデプロイ可能な形式に変換
** AI ModelをエッジAIデバイスにデプロイ
** ユーザーが自分で作成した「**DeviceApp**」を「**Console**」にアップロード
*** アップロードした「**DeviceApp**」の確認と削除
** 「**DeviceApp**」をエッジAIデバイスにデプロイ

== 機能概要、アルゴリズム
[#_Functional-Overview]
=== Functional Overview
* 「**Console**」にアクセス可能なClientを生成する
** 「**Console**」アクセスに必要な情報をConfigに設定し、ConfigをClientに設定する
+
「**Console**」アクセスに必要な情報は下記である
+
|===
|Name |Description

|Console endpoint
|APIサーバ・ベースURL

|Authorization endpoint
|アクセストークンを発行する認証サーバURL

|Client ID
|アクセストークン発行に必要なClient ID

|Client Secret
|アクセストークン発行に必要なClient Secret

|===

* Clientから機能毎に分類された「**Console**」のAPIを実行する
+
[TIP]
====
機能毎の分類は、「**Console**」が提供する「**Low Level SDK**」のAPIの分類に従います。 +
「**Console**」アクセスに必要なアクセストークンの取得と更新をします。（Wrap）
====
+
[TIP]
====
APIにtimeoutの引数がない場合にはtimeoutしない。
====
** DeviceManagement
*** get_devices / エッジAIデバイスの情報一覧取得
*** start_upload_inference_result / 推論結果メタデータ取得開始
*** stop_upload_inference_result / 推論結果メタデータ取得停止
*** get_command_parameter_file / 「**Console**」に登録されたcommand parameter fileの一覧取得
** AI Model
*** import_base_model / ベースモデルのインポート
*** get_models / モデル情報一覧取得
*** get_base_model_status / ベースモデル情報取得
*** delete_model / モデル削除
*** publish_model / モデル発行
** Deployment
*** import_device_app / 「**DeviceApp**」のインポート
*** get_device_apps / 「**DeviceApp**」の情報一覧取得
*** delete_device_app / 「**DeviceApp**」の削除
*** get_deploy_configurations / デプロイconfig情報一覧取得
*** create_deploy_configuration / デプロイconfig情報登録
*** deploy_by_configuration / デプロイ
*** get_deploy_history / デプロイ履歴取得
*** delete_deploy_configuration / デプロイconfig情報削除
*** cancel_deployment / デプロイ状態強制キャンセル
*** deploy_device_app / 「**DeviceApp**」のデプロイ
*** undeploy_device_app / 「**DeviceApp**」のアンデプロイ
*** get_device_app_deploys / 「**DeviceApp**」のデプロイ履歴取得
** Insight
*** get_image_directories / 画像保存ディレクトリ一覧取得
*** get_images / 保存済み画像取得
*** get_inference_results / 保存済み推論結果メタデータ一覧取得
*** export_images / 保存済み画像エクスポート

* 「**Low Level SDK**」のAPIをユースケースでまとめたHigh Level APIを実行することができます。
** AI Model
*** publish_model_wait_response / モデル発行し、完了待ち
** Deployment
*** deploy_by_configuration_wait_response / デプロイし、完了待ち
*** deploy_device_app_wait_response / 「**DeviceApp**」をデプロイし、完了待ち
** Insight
*** get_image_data / 保存済み画像取得
**** get_imagesは、最大256件取得のため、本APIはget_imagesを複数回呼び出し、制限を隠蔽
*** get_last_inference_data / 保存済み推論結果の最新データ取得
*** get_last_inference_and_image_data / 保存済み推論結果と画像の最新データ取得
**** Dateの最も新しい画像を取得し、画像に紐づく推論結果を探して返却

* 「**Console Access Library**」の実行時、コンソールにログの出力を行う
** ログフォーマットは下記の通りに定義する
*** [ログ出力時刻] [ログレベル] [クライアント名] : メッセージ本文
*** ログ出力時刻は、ユーザーが利用する環境のシステム時刻を使用する
*** ログ出力時刻は、ISO 8601形式で日付+時刻+タイムゾーンを出力する
*** ログ出力例: +
2022-06-21T11:31:42.612+0900 ERROR ConsoleAccessClient : Failed to log request

** ログレベルを指定して、出力するログレベルを切り替えられる
*** ログレベルは下記の通りに定義する
+
[%header%autowidth]
|===
|Level |Summary 

|ERROR
|「**Console Access Library**」の実行時、正常に処理を終了できなかった場合に使用する

|WARNING
|異常とは言い切れないが正常とも異なる、何らかの予期しない問題が発生したときに使用する

|INFO
|「**Console Access Library**」がイベントを実行する際に使用する

|DEBUG
|「**Console Access Library**」の動作状況等、詳細なデバッグ情報を使用する

|OFF
|全てのログを無効にする
|===
*** 指定したログレベル以上のログを出力する +
例) INFOを指定するとINFO/WARNING/ERRORを出力し、DEBUGは出力しない
*** 指定したログレベルがOFFの場合は、全てのログレベルを出力しない
*** 既定のログレベルはOFFとする
*** ログレベルの指定は、ライブラリを利用するアプリケーション側で開発言語毎に指定された手順で行う
+
[%header]
|===
|Pythonでの指定例
a|
[source,python]
----
import console_access_library

# Set the desired logging level
console_access_library.set_logger(level=logging.WARNING)
----
|===

* 「**Console Access Library**」の実行時、エラー条件の確認を行う
** 下記の条件でエラーと判断する
*** APIの入力パラメータが不適
*** APIの入力パラメータは適切だが、 「**Low Level SDK**」からの応答が期待通りではない(Timeout/Errorなど)
*** 「**Console**」に正常に接続できない(認証エラー、URL誤り、など)

=== Algorithm
* 「**Console Access Library**」使用開始
. 「**Cloud App**」でConfigを作成
+
. 「**Cloud App**」からのClientを作成
+
Client生成時には、アクセストークンの取得、「**Low Level SDK**」の生成
. Client instanceから「**Low Level SDK**」のAPIをWrapしたAPI、機能複合したAPI（High Level API）を利用
+
「**Low Level SDK**」のAPIをWrapしたAPI内で、「**Console**」へのアクセスに必要なアクセストークンの取得、更新
+
- アクセストークンの有効期限は1時間となっており、有効期限が残り180秒以下の場合、アクセストークンの更新

* 推論結果メタデータ取得開始 - 停止
. get_devices APIで、デバイスのIDを確認
. start_upload_inference_result APIで推論結果メタデータ取得開始
. InsightのAPIを使用して、推論結果、画像の取得
. stop_upload_inference_result APIで推論結果メタデータ取得停止


=== Under what condition
* 「**Console**」のAPIへのアクセスは「**Low Level SDK**」を使用すること

=== API
* Config
** constructor(console_endpoint: str, portal_authorization_endpoint: str, client_id: str, client_secret: str)

* Client
** constructor(config)
** get_device_management()
** get_ai_model()
** get_deployment()
** get_insight()

* DeviceManagement
** get_devices(device_id: str, device_name: str, connection_state: str, device_group_id: str)
** start_upload_inference_result(device_id: str)
** stop_upload_inference_result(device_id: str)
** get_command_parameter_file()

* AI Model
** import_base_model(model_id: str, model: str, converted: bool, vendor_name: str, comment: str, input_format_param: str, network_config: str, network_type: str, labels: [])
** get_models(model_id: str, comment: str, project_name: str, model_platform: str, project_type: str, device_id: str, latest_type: str)
** get_base_model_status(model_id: str, latest_type: str)
** delete_model(model_id: str)
** publish_model(model_id: str, device_id: str)

* AI Model High Level API
** publish_model_wait_response(model_id: str, device_id: str, callback: publish_model_wait_response_callback)
*** publish_model_wait_response_callback(status: str)

* Deployment
** import_device_app(compiled_flg: str, app_name: str, version_number: str, file_name: str, file_content: str, entry_point: str, comment: str)
** get_device_apps()
** delete_device_app(app_name: str, version_number: str)
** get_deploy_configurations()
** create_deploy_configuration(config_id: str, comment: str, sensor_loader_version_number: str, sensor_version_number: str, model_id: str, model_version_number: str, ap_fw_version_number: str)
** deploy_by_configuration(config_id: str, device_ids: str, replace_model_id: str, comment: str)
** get_deploy_history(device_id: str)
** delete_deploy_configuration(config_id: str)
** cancel_deployment(device_id: str, deploy_id: str)
** deploy_device_app(app_name: str, version_number: str, device_ids: str, deploy_parameter: str, comment: str)
** undeploy_device_app(device_ids: str)
** get_device_app_deploys(app_name: str, version_number: str)

* Deployment High Level API
** deploy_by_configuration_wait_response(config_id: str, device_ids: str, replace_model_id: str, comment: str, timeout: int, callback: deploy_by_configuration_wait_response_callback)
*** deploy_by_configuration_wait_response_callback(device_status_array: list)
** deploy_device_app_wait_response(app_name: str, version_number: str, device_ids: str, deploy_parameter: str, comment: str, callback: deploy_device_app_wait_response_callback)
*** deploy_device_app_wait_response_callback(device_status_array: list)

* Insight
** get_image_directories(device_id: str)
** get_images(device_id: str, sub_directory_name: str, number_of_images: int, skip: int, order_by: str)
** get_inference_results(device_id: str, filter: str, number_of_inference_results: int, raw: int, time: str)
** export_images(key: str, from_datetime: str, to_datetime: str, device_id: str, file_format: str)

* Insight High Level API
** get_image_data(device_id: str, sub_directory_name: str, number_of_images: int, skip: int, order_by: str)
** get_last_inference_data(device_id: str)
** get_last_inference_and_image_data(device_id: str, sub_directory_name: str)

=== Others Exclusive conditions / specifications
* command parameter fileをエッジAIデバイスに適用済みであること

== 操作性仕様、画面仕様
* なし

== 各BlockでのAPIパラメータ
各エラーメッセージは、関数名が言語によって異なる（この資料では代表してPythonでのエラーメッセージを記載）

* Config
** constructor: コンストラクタ
+
【Error：console_endpointが空の場合】E001 : console_endpoint is required.
+
【Error：portal_authorization_endpointが空の場合】E001 : portal_authorization_endpoint is required.
+
【Error：client_idが空の場合】E001 : client_id is required.
+
【Error：client_secretが空の場合】E001 : client_secret is required.
+
|===
|Parameter’s name|Meaning|Range of parameter

|console_endpoint
|「**Console**」のアクセス先URL
|なし +
指定なしの場合、環境変数から読み出す

|portal_authorization_endpoint
|「**Console**」へのアクセスに必要なアクセストークン発行先URL
|なし +
指定なしの場合、環境変数から読み出す

|client_id
|アクセストークン発行に必要なClient ID
|なし +
指定なしの場合、環境変数から読み出す

|client_secret
|アクセストークン発行に必要なClient Secret
|なし +
指定なしの場合、環境変数から読み出す

|===
+
|===
|Return value|Meaning

|Config instance
|「**Console**」へのアクセスに必要な情報を保持したconfig instance
|===

* Client
** constructor: コンストラクタ
+
|===
|Parameter’s name|Meaning|Range of parameter

|config
|「**Console**」へのアクセスに必要な情報を保持したconfig instance
|なし

|===
+
|===
|Return value|Meaning

|Client instance
|「**Low Level SDK**」のAPIをWrapしたAPI、機能複合したAPI（High Level API）を実行可能なclient instance
|===

** get_device_management: DeviceManagement APIを提供するInstanceの取得
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|DeviceManagement instance
|DeviceManagement APIを提供するInstance
|===

** get_ai_model: AI Model APIを提供するInstanceの取得
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|AI Model instance
|AI Model APIを提供するInstance
|===

** get_deployment: Deployment APIを提供するInstanceの取得
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|Deployment instance
|Deployment APIを提供するInstance
|===

** get_insight: Insight APIを提供するInstanceの取得
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|Insight instance
|Insight APIを提供するInstance
|===

* DeviceManagement
** get_devices: エッジAIデバイスの情報一覧取得
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_id
|エッジAIデバイスのID
|部分検索、大文字小文字は区別しない +
指定なしの場合、全device_id検索

|device_name
|エッジAIデバイスの名前
|部分検索、大文字小文字は区別しない +
指定なしの場合、全device_name検索

|connection_state
|接続状態
|接続状態の場合: Connected +
切断状態の場合: Disconnected +
完全一致検索、大文字小文字は区別しない +
指定なしの場合、全connection_state検索

|device_group_id
|エッジAIデバイスの所属グループ
|完全一致検索、大文字小文字は区別しない +
指定なしの場合、全device_group_id検索

|===
+
|===
|Return value|Meaning

|Device information
|エッジAIデバイスの情報
|===

** start_upload_inference_result: 推論結果メタデータ取得開始
+
【Error：device_idが空の場合】E001 : device_id is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する

|===
+
|===
|Return value|Meaning

|result
|実行結果

|outputSubDirectory
|Input Image格納パス、UploadMethod:Blob Storageのみ

|===

** stop_upload_inference_result: 推論結果メタデータ取得停止
+
【Error：device_idが空の場合】E001 : device_id is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** get_command_parameter_file: 「**Console**」に登録されたcommand parameter fileの一覧取得
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|result
|「**Console**」に登録されているCommandParameterの一覧

|===

* AI Model
** import_base_model: ベースモデルのインポート
+
【Error：model_idが空の場合】E001 : model_id is required.
+
【Error：modelが空の場合】E001 : model is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|model_id
|モデルID(新規保存またはバージョンアップ対象のモデルID)
|100文字以内 +
下記以外は禁則文字 +
半角英数字 +
- ハイフン +
_ アンダーバー +
() 小括弧 +
. ドット

|model
|モデルファイル  SAS URI
|なし

|converted
|変換済みフラグ
|True: 変換後モデル +
False: 変換前モデル +
指定なしの場合、False

|vendor_name
|ベンダー名（新規保存の場合に指定）
|100文字以内 +
バージョンアップの場合指定しない +
指定なしの場合、ベンダー名なし

|comment
|モデルを新規登録する際に入力するモデルに関する説明 +
新規保存時はモデルとバージョンの説明として設定される +
バージョンアップ時はバージョンの説明として設定される
|100文字以内
指定なしの場合、モデルを新規登録する際に入力するモデルに関する説明なし

|input_format_param
|input format paramファイル（json形式）のURI +
下記について評価を実施 +
 Azure：SAS URI +
 AWS：  Presigned URI +
用途：Packagerの変換情報(image format情報)
|SAS URI形式以外は禁則文字 +
jsonの形式はオブジェクトの配列(各オブジェクトは下記値を含む) +
例 +
ordinal: コンバータへのDNN入力の順序（値範囲：0～2） +
format: フォーマット（"RGB" or "BGR"） +
指定なしの場合、評価しない

|network_config
|network config ファイル（json形式）のURI +
下記について評価を実施 +
 Azure：SAS URI +
 AWS：  Presigned URI +
変換前モデルの場合、指定する(=変換後モデルの場合、無視する) +
用途：model converterの変換パラメータ情報
|SAS URI形式以外は禁則文字 +
指定なしの場合、評価しない

|network_type
|ネットワーク種別(モデル新規登録の場合のみ有効)
|0：Custom Vision +
1：Non Custom Vision +
指定なしの場合、1


|labels
|ラベル名
|例: ["label01","label02","label03"]

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** get_models: モデル情報一覧取得
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|model_id
|モデルID
|部分検索 +
指定なしの場合、全model_id検索

|comment
|モデル説明
|部分検索 +
指定なしの場合、全comment検索

|project_name
|プロジェクト名
|部分検索 +
指定なしの場合、全project_name検索

|model_platform
|モデルプラットフォーム
|0 : Custom Vision +
1 : Non Custom Vision +
2 : Model Retrainer +
完全一致検索 +
指定なしの場合、全model_platform検索

|project_type
|プロジェクト種別
|0 : ベース +
1 : デバイス +
完全一致検索 +
指定なしの場合、全project_type検索

|device_id
|エッジAIデバイスのID(デバイスモデルを検索したい場合に指定)
|完全一致検索 +
大文字小文字を区別する +
指定なしの場合、全device_id検索

|latest_type
|最新バージョン種別
|0 : 発行済み最新バージョン +
1 : 最新バージョン(変換/発行処理中モデルバージョンも含めた最新) +
完全一致検索 +
指定なしの場合、1

|===
+
|===
|Return value|Meaning

|Model information
|モデル情報

|===

** get_base_model_status: ベースモデル情報取得
+
【Error：model_idが空の場合】E001 : model_id is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|model_id
|モデルID
|なし

|latest_type
|最新バージョン種別
|0 : 発行済み最新バージョン +
1 : 最新バージョン(変換/発行処理中モデルバージョンも含めた最新) +
完全一致検索 +
指定なしの場合、1

|===
+
|===
|Return value|Meaning

|Base Model information
|ベースモデル情報

|===

** delete_model: モデル削除
+
【Error：model_idが空の場合】E001 : model_id is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|model_id
|モデルID
|なし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** publish_model: モデル発行
+
【Error：model_idが空の場合】E001 : model_id is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|model_id
|モデルID
|なし

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する +
デバイスモデルが対象の場合に指定する +
ベースモデルが対象の場合、指定しない

|===
+
|===
|Return value|Meaning

|result
|実行結果

|import_id
|インポートID

|===

** publish_model_wait_response: モデル発行し、完了待ち
+
【Error：model_idが空の場合】E001 : model_id is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|model_id
|モデルID
|なし

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する +
デバイスモデルが対象の場合に指定する +
ベースモデルが対象の場合、指定しない

|callback
|コールバック関数
|get_base_model_statusで処理結果確認し、コールバック関数を呼び出して処理状況通知 +
指定なしの場合、コールバック通知なし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|process time
|処理時間

|===

** publish_model_wait_response_callback: publish_model_wait_responseの状態通知Callback
+
|===
|Parameter’s name|Meaning|Range of parameter

|status
|Publish状態
|'01': 'Before conversion' +
'02': 'Converting' +
'03': 'Conversion failed' +
'04': 'Conversion complete' +
'05': 'Adding to configuration' +
'06': 'Add to configuration failed' +
'07': 'Add to configuration complete' +
'11': 'Saving'(Model Retrainerの場合のモデル保存中ステータス)

|===
+
|===
|Return value|Meaning

|-
|-

|===

* Deployment
** import_device_app: 「**DeviceApp**」インポート
+
【Error：compiled_flgが空の場合】E001 : compiled_flg is required.
+
【Error：app_nameが空の場合】E001 : app_name is required.
+
【Error：version_numberが空の場合】E001 : version_number is required.
+
【Error：file_nameが空の場合】E001 : file_name is required.
+
【Error：file_contentが空の場合】E001 : file_content is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|compiled_flg
|コンパイルフラグ
|0:未コンパイル(コンパイル処理を行う) +
1:コンパイル済み(コンパイル処理を行わない)

|app_name
|「**DeviceApp**」名
|文字数上限は、app_name + version_number <=31 とする +
下記以外は禁則文字 +
・英数字 +
・アンダーバー +
・ドット

|version_number
|「**DeviceApp**」バージョン
|文字数上限は、app_name + version_number <=31 とする +
下記以外は禁則文字 +
・英数字 +
・アンダーバー +
・ドット

|file_name
|「**DeviceApp**」ファイル名
|なし

|file_content
|「**DeviceApp**」ファイル内容
|Base64 Encodeされた文字列

|entry_point
|「**EVPモジュール**」のエントリポイント
|なし +
指定なしの場合、"ppl"

|comment
|「**DeviceApp**」説明
|100文字以内 +
指定なしの場合、コメントなし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** get_device_apps: 「**DeviceApp**」情報一覧取得
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|DeviceApp information
|「**DeviceApp**」情報

|===

** delete_device_app: 「**DeviceApp**」削除
+
【Error：app_nameが空の場合】E001 : app_name is required.
+
【Error：version_numberが空の場合】E001 : version_number is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|app_name
|「**DeviceApp**」名
|なし

|version_number
|「**DeviceApp**」バージョン
|なし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** get_deploy_configurations: デプロイconfig情報一覧取得
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|-
|-
|-

|===
+
|===
|Return value|Meaning

|DeployConfiguration information
|DeployConfiguration情報

|===

** create_deploy_configuration: デプロイconfig情報登録
+
【Error：config_idが空の場合】E001 : config_id is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|config_id
|config ID
|20文字以内 +
下記以外は禁則文字 +
半角英数字 +
- ハイフン +
_ アンダーバー +
() 小括弧 +
. ドット

|comment
|Config説明
|100文字以内 +
指定なしの場合、コメントなし

|sensor_loader_version_number
|SensorLoaderバージョン番号
|-1を指定した場合、デフォルトバージョン(システム設定「DVC0017」)を適用 +
指定なしの場合SensorLoaderデプロイなし

|sensor_version_number
|Sensorバージョン番号
|-1を指定した場合、デフォルトバージョン(システム設定「DVC0018」)を適用 +
指定なしの場合Sensorデプロイなし

|model_id
|モデルID
|指定なしの場合、モデルデプロイなし

|model_version_number
|モデルバージョン番号
|指定なしの場合、最新のVersionを適用

|ap_fw_version_number
|ApFwバージョン番号
|指定なしの場合、ファームウェアデプロイなし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** deploy_by_configuration: デプロイ
+
【Error：config_idが空の場合】E001 : config_id is required.
+
【Error：device_idsが空の場合】E001 : device_ids is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|config_id
|config ID
|なし

|device_ids
|エッジAIデバイスのIDs
|カンマ区切りで複数のエッジAIデバイスのIDを指定 +
大文字小文字を区別する

|replace_model_id
|入替対象モデルID
|「model_id」または「network_id」を指定 +
指定されたモデルIDのものがDBに存在しない場合、入力された値をnetwork_id(「**Console**」の内部管理ID)としてみなし、処理を行う +
指定なしの場合、入替しない.

|comment
|デプロイコメント
|100文字以内 +
指定なしの場合、コメントなし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** get_deploy_history: デプロイ履歴取得
+
【Error：device_idが空の場合】E001 : device_id is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する

|===
+
|===
|Return value|Meaning

|deploy history
|デプロイ履歴

|===

** delete_deploy_configuration: デプロイconfig情報削除
+
【Error：config_idが空の場合】E001 : config_id is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|config_id
|config ID
|なし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** cancel_deployment: デプロイ状態強制キャンセル
+
【Error：device_idが空の場合】E001 : device_id is required.
+
【Error：deploy_idが空の場合】E001 : deploy_id is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する

|deploy_id
|デプロイID
|get_deploy_historyで取得出来るid

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** deploy_device_app: 「**DeviceApp**」デプロイ
+
【Error：app_nameが空の場合】E001 : app_name is required.
+
【Error：version_numberが空の場合】E001 : version_number is required.
+
【Error：device_idsが空の場合】E001 : device_ids is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|app_name
|App名
|なし

|version_number
|Appバージョン
|なし

|device_ids
|エッジAIデバイスのIDs
|カンマ区切りで複数のエッジAIデバイスのIDを指定 +
大文字小文字を区別する

|deploy_parameter
|デプロイパラメータ
|JsonフォーマットをBase64 Encodeされた文字列 +
指定なしの場合、パラメータなし

|comment
|デプロイコメント
|100文字以内 +
指定なしの場合、コメントなし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** undeploy_device_app: 「**DeviceApp**」アンデプロイ
+
【Error：device_idsが空の場合】E001 : device_ids is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_ids
|エッジAIデバイスのID
|カンマ区切りで複数のエッジAIデバイスのIDを指定 +
大文字小文字を区別する

|===
+
|===
|Return value|Meaning

|result
|実行結果

|===

** get_device_app_deploys: 「**DeviceApp**」デプロイ履歴取得
+
【Error：app_nameが空の場合】E001 : app_name is required.
+
【Error：version_numberが空の場合】E001 : version_number is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|app_name
|App名
|なし

|version_number
|Appバージョン
|なし

|===
+
|===
|Return value|Meaning

|DeviceApp deploy history
|「**DeviceApp**」デプロイ履歴

|===

** deploy_by_configuration_wait_response: デプロイし、完了待ち
+
【Error：config_idが空の場合】E001 : config_id is required.
+
【Error：device_idsが空の場合】E001 : device_ids is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|config_id
|config ID
|なし

|device_ids
|エッジAIデバイスのIDs
|カンマ区切りで複数のエッジAIデバイスのIDを指定 +
大文字小文字を区別する

|replace_model_id
|入替対象モデルID
|「model_id」または「network_id」を指定 +
指定されたモデルIDのものがDBに存在しない場合、入力された値をnetwork_id(「**Console**」の内部管理ID)としてみなし、処理を行う +
指定なしの場合、入替しない.

|comment
|デプロイコメント
|100文字以内 +
指定なしの場合、コメントなし

|timeout
|完了待ちのtimeout時間 +
デプロイ処理でエッジAIデバイスがハングアップするなどで、処理中のままとなるケースがあるため、処理を抜けるtimeout
|なし +
指定なしの場合、3600秒

|callback
|コールバック関数 +
get_deploy_historyで処理結果確認し、コールバック関数を呼び出して処理状況通知
|指定なしの場合、コールバック通知なし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|process time
|処理時間

|===

** deploy_by_configuration_wait_response_callback: deploy_by_configuration_wait_responseの状態通知Callback
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_status_array
|エッジAIデバイスのDeploy状態リスト
|下記形式 +
[ +
　{ +
　　<device_id>: { +
　　　"status":<status> +
　　} +
　}, +
] +

deploy_by_configuration_wait_responseのdevice_idsで指定したdevice_id分のデータが入る +

<device_id>: エッジAIデバイスのID +
<status>: 下記のデプロイ状態を格納 +
　0：デプロイ中 +
　1：正常終了 +
　2：失敗 +
　3：キャンセル +
　9：「**DeviceApp**」アンデプロイ

|===
+
|===
|Return value|Meaning

|-
|-

|===

** deploy_device_app_wait_response: 「**DeviceApp**」デプロイし、完了待ち
+
【Error：app_nameが空の場合】E001 : app_name is required.
+
【Error：version_numberが空の場合】E001 : version_number is required.
+
【Error：device_idsが空の場合】E001 : device_ids is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|app_name
|App名
|なし

|version_number
|Appバージョン
|なし

|device_ids
|エッジAIデバイスのIDs
|カンマ区切りで複数のエッジAIデバイスのIDを指定 +
大文字小文字を区別する

|deploy_parameter
|デプロイパラメータ
|JsonフォーマットをBase64 Encodeされた文字列 +
指定なしの場合、パラメータなし

|comment
|デプロイコメント
|100文字以内 +
指定なしの場合、コメントなし

|callback
|コールバック関数 +
get_device_app_deploysで処理結果確認し、コールバック関数を呼び出して処理状況通知
|指定なしの場合、コールバック通知なし

|===
+
|===
|Return value|Meaning

|result
|実行結果

|process time
|処理時間

|===

** deploy_device_app_wait_response_callback: deploy_device_app_wait_responseの状態通知Callback
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_status_array
|エッジAIデバイスのDeploy状態リスト
|下記形式 +
[ +
　{ +
　　<device_id>: { +
　　　"status":<status>, +
　　　"found_position":<found_position>, +
　　　"skip":<skip> +
　　} +
　}, +
] +

deploy_device_app_wait_responseのdevice_idsで指定したdevice_id分のデータが入る +

<device_id>: エッジAIデバイスのID +
<found_position>: get_device_app_deploysレスポンスに格納されるdevice_idsのindex +
<skip>: 下記の値を格納 +
　0: get_device_app_deploysレスポンスに格納される最新のstatusの場合 +
　1: get_device_app_deploysレスポンスに格納される最新以外のstatusの場合 +
<status>: 下記のデプロイ状態を格納 +
　0：デプロイ中 +
　1：正常終了 +
　2：失敗 +
　3：キャンセル +

|===
+
|===
|Return value|Meaning

|-
|-

|===

* Insight
** get_image_directories: 画像保存ディレクトリ一覧取得
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する +
指定なしの場合、全てのdevice_idの情報を返す

|===
+
|===
|Return value|Meaning

|Image save directory information
|画像保存ディレクトリ情報
|===

** get_images: 保存済み画像取得
+
【Error：device_idが空の場合】E001 : device_id is required.
+
【Error：sub_directory_nameが空の場合】E001 : sub_directory_name is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する

|sub_directory_name
|画像保存のサブディレクトリ
|なし +
サブディレクトリは、start_upload_inference_resultの応答で通知されるdirectory、または、get_image_directoriesで取得したdirectory

|number_of_images
|画像の取得数
|0-256 +
指定なしの場合:50

|skip
|取得をスキップする画像の数
|なし +
指定なしの場合:0

|order_by
|ソート順：画像の作成された日時によるソート順
|DESC、ASC、desc、asc +
指定なしの場合:ASC

|===
+
|===
|Return value|Meaning

|Total image count
|全画像数

|Image filename and image content
|画像ファイル名と、画像ファイルデータ（Base64 Encode済みデータ）
|===

** get_inference_results: 保存済み推論結果メタデータ一覧取得
+
【Error：device_idが空の場合】E001 : device_id is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する

|filter
|検索フィルタ(AzureポータルのCosmos DB UIと下記以外は同じ仕様) +
- where文字列を先頭に付加する必要はない +
- device_idを付加する必要はない
|なし

|number_of_inference_results
|取得件数
|なし +
指定なしの場合:20

|raw
|推論結果のデータ形式
|1:Cosmos DBに格納されたままのレコードを付加 +
0:付与しない +
指定なしの場合:1

|time
|Cosmos DBに格納された推論結果データのタイムスタンプ
|yyyyMMddHHmmssfff +
- yyyy: 4桁の年の文字列 +
- MM: 2桁の月の文字列 +
- dd: 2桁の日の文字列 +
- HH: 2桁の時間の文字列 +
- mm: 2桁の分の文字列 +
- ss: 2桁の秒の文字列 +
- fff: 3桁のミリ秒の文字列

|===
+
|===
|Return value|Meaning

|inference data
|推論結果
|===

** export_images: 保存済み画像エクスポート
+
【Error：keyが空の場合】E001 : key is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|key
|RSA公開鍵
|Base64 Encodeされた文字列

|from_datetime
|日時(From)
|yyyyMMddhhmm形式 +
指定なしの場合、Fromの範囲設定なし

|to_datetime
|日時(To)
|yyyyMMddhhmm形式 +
指定なしの場合、Toの範囲設定なし

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する +
指定なしの場合、全device_id指定

|file_format
|画像ファイルフォーマット
|JPG、BMP、RAW +
指定しない場合、絞り込みなし

|===
+
|===
|Return value|Meaning

|key
|共通鍵 +
公開鍵で暗号化された画像復号化用の共通鍵

|url
|ダウンロード用のSUS URI

|===

** get_image_data: 保存済み画像取得
+
【Error：device_idが空の場合】E001 : device_id is required.
+
【Error：sub_directory_nameが空の場合】E001 : sub_directory_name is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する

|sub_directory_name
|画像保存のサブディレクトリ
|なし +
サブディレクトリは、start_upload_inference_resultの応答で通知されるdirectory、または、get_image_directoriesで取得したdirectory

|number_of_images
|画像の取得数
|なし +
指定なしの場合:50

|skip
|取得をスキップする画像の数
|なし +
指定なしの場合:0

|order_by
|ソート順：画像の作成された日時によるソート順
|DESC、ASC、desc、asc +
指定なしの場合:ASC

|===
+
|===
|Return value|Meaning

|Total image count
|全画像数

|Image filename and image content
|画像ファイル名と、画像ファイルデータ（Base64 Encode済みデータ）
|===

** get_last_inference_data: 保存済み推論結果の最新データ取得
+
【Error：device_idが空の場合】E001 : device_id is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する

|===
+
|===
|Return value|Meaning

|inference data
|推論結果
|===

** get_last_inference_and_image_data(): 保存済み推論結果と画像の最新データ取得
+
【Error：device_idが空の場合】E001 : device_id is required.
+
【Error：sub_directory_nameが空の場合】E001 : sub_directory_name is required.
+
【Error：「**Low Level SDK**」にてErrorが発生した場合】「**Console Access Library**」で定義したErrorを発生させる
+
【Error：「**Low Level SDK**」のAPIから返却されたhttp_statusが200以外の場合】「**Console Access Library**」で定義したErrorを発生させる
+
|===
|Parameter’s name|Meaning|Range of parameter

|device_id
|エッジAIデバイスのID
|大文字小文字を区別する

|sub_directory_name
|画像保存のサブディレクトリ
|なし +
サブディレクトリは、start_upload_inference_resultの応答で通知されるdirectory、または、get_image_directoriesで取得したdirectory

|===
+
|===
|Return value|Meaning

|inference data and image data
|推論結果と画像データ（Base64 Encode済みデータ）
|===

== ログ出力メッセージ
レベル毎に表示するメッセージは下記の通り定義する

=== ERRORレベル
[%header%autowidth]
|===
|MessageID |Conditions |Message |Parameter
|E001
|必要な引数が渡されなかった際に出力される
|{0} is required.
|{0}:渡されなかった引数名
|===

=== WARNINGレベル
[%header%autowidth]
|===
|MessageID |Conditions |Message |Parameter
|W001
|非推奨になったクラスや関数を呼び出した際に出力される
|{0} has been deprecated.
|{0}:呼び出されたクラスや関数名
|===

=== INFOレベル
T.B.D.

=== DEBUGレベル
T.B.D.

== 目標性能
* なし

== 制限事項
* なし

== その他特記事項
* なし

== 未決定事項
* なし
