= Cloud SDK pass:[<br/>] Console Access Library pass:[<br/>] Python版 pass:[<br/>] チュートリアル pass:[<br/>]
:sectnums:
:sectnumlevels: 1
:author: Copyright 2023 Sony Semiconductor Solutions Corporation
:version-label: Version 
:revnumber: x.x.x
:revdate: YYYY - MM - DD
:trademark-desc: AITRIOS™、およびそのロゴは、ソニーグループ株式会社またはその関連会社の登録商標または商標です。
:toc:
:toc-title: 目次
:toclevels: 1
:chapter-label:
:lang: ja

== 目的

このチュートリアルでは「**Console Access Library**」が公開する各種APIについて解説します。本書を通じてLibraryをビルドして使用できるようになります。

== 前提条件
- Python 3.8.10
- Python依存関係

    * requests>=2.31.0
    * jsonschema>=4.6.2
    * setuptools>=65.5.1
    * wheel>=0.37.1
    * PyYAML>=6.0
    * marshmallow>=3.17.0
    * pytest>=7.1.2
    * pytest-html-reporter>=0.2.9
    * pytest-ordering>=0.6
    * sphinx==4.3.2
    * myst-parser>=0.18.0
    * sphinx-rtd-theme>=1.0.0
    * sphinxcontrib-napoleon>=0.7
    * rst2pdf>=0.99
    * streamlit==1.11.1
    * pytest-timeout>=2.1.0
    * PyJWT>=2.6.0
    * nassl>=4.0
    * cryptography>=36.0
    * validators>=0.18
    * msal>=1.22.0

=== 「**Console Access Library**」 API仕様
「**Console Access Library**」のAPI仕様を参照する方法は、下記の手順を参照してください。

1. リポジトリをクローンします
    ** https://github.com/SonySemiconductorSolutions/aitrios-sdk-console-access-lib-python

2. クローンしたディレクトリ内に存在する `**docs/api-reference/index.html**` をウェブブラウザで開きます

== 使用法

=== インストール

. リポジトリをクローンします

. デモアプリケーション用にPython依存関係をインストールします
+
```
    pip install -r requirements.txt
```

. 次のコマンドを実行してPython環境へのインストールを行います
+
```
    python -m pip install lib/python_client.
```

. 次のコマンドを実行してPython環境へのインストールを行います
+
```
    python -m pip install src/.
```

. ネットワークProxy設定
+
プロキシ環境で「**Console Access Library**」を使用するには `**https_proxy**` 環境変数を設定します
+
```
    export https_proxy=http://username:password@proxyhost:port
```

<<<

=== 「**Console Access Library**」サンプルアプリケーション開始用のパラメータ設定

==== オプション1: Console Access設定ファイルを使用

* 手順1: Console Access設定ファイルを作成してユーザー環境値を入力します
+
`samples/console_access_settings.yaml`
+

|===
|「**Console Developer Edition**」使用時
a|
[source,Yaml]
----
    console_access_settings:
        console_endpoint: "__console_endpoint__"
        portal_authorization_endpoint: "__portal_authorization_endpoint__"
        client_secret: "__client_secret__"
        client_id: "__client_id__"
----
|===

+

|===
|「**Console Enterprise Edition**」使用時
a|
[source,Yaml]
----
    console_access_settings:
        console_endpoint: "__base_url__"
        portal_authorization_endpoint: "https://login.microsoftonline.com/'__tenant_id__'"
        client_secret: "__creant_secret__"
        client_id: "__client_id__"
        application_id: "__application_id__"
----
|===

* 手順2: モジュール `**ReadConsoleAccessSettings**`, `**Config**`, `**Client**` を「**Console Access Library**」サンプルアプリケーションにインポートします
+
|===
|samples/demo-console/src/controller/apiexecutor.ts
a|
[source,python]
----
    from console_access_library.common.read_console_access_settings import ReadConsoleAccessSettings
    from console_access_library.common.config import Config
    from console_access_library.client import Client
----
|===

* 手順3: Console Access設定ファイルのパスを設定し、「**Console Access Library**」 `**ReadConsoleAccessSettings**` のインスタンスを生成します `**console_access_settings.yaml**` ファイルを作成するには、手順1を参照してください
+

|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    SETTING_FILE_PATH = os.path.join(os.getcwd(), "samples", "console_access_settings.yaml")
    read_console_access_settings_obj = ReadConsoleAccessSettings(SETTING_FILE_PATH)
----
|===

* 手順4: 「**Console Access Library**」 `**Config**` のインスタンスを生成します
+

|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    config_obj = Config(console_endpoint=read_console_access_settings_obj.console_endpoint,
                        portal_authorization_endpoint=read_console_access_settings_obj.portal_authorization_endpoint,
                        client_id=read_console_access_settings_obj.client_id,
                        client_secret=read_console_access_settings_obj.client_secret,
                        application_id=read_console_access_settings_obj.application_id)
----
|===
<<<

==== オプション2: Console Access設定ファイルを作成せずにユーザー環境値を環境変数にエクスポート

* 手順1: ユーザー環境値を環境変数にexportします
+
```
    export CONSOLE_ENDPOINT="__console_endpoint__"
    export PORTAL_AUTHORIZATION_ENDPOINT="__portal_authorization_endpoint__"
    export CLIENT_SECRET="__client_secret__"
    export CLIENT_ID="__client_id__"
    export APPLICATION_ID="__application_id__"
```
* 手順2: モジュール `**Config**`, `**Client**` を「**Console Access Library**」サンプルアプリケーションにインポートします
+
|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    from console_access_library.common.config import Config
    from console_access_library.client import Client
----
|===

* 手順3: 「**Console Access Library**」 `**Config**` のインスタンスを生成します
+

|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    config_obj = Config(console_endpoint=None,
                        portal_authorization_endpoint=None,
                        client_id=None,
                        client_secret=None,
                        application_id=None)
----
|===


==== オプション3: 「**Console Access Library**」へユーザー環境値設定

* 手順1: モジュール `**Config**`, `**Client**` を「**Console Access Library**」サンプルアプリケーションにインポートします
+
|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    from console_access_library.common.config import Config
    from console_access_library.client import Client
----
|===

* 手順2: 「**Console Access Library**」 `**Config**` のインスタンスをユーザー環境値で生成します
+
|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    config_obj = Conf(console_endpoint="__console_endpoint__", 
                        portal_authorization_endpoint="__portal_authorization_endpoint__",
                        client_id="__client_id__", 
                        client_secret="__client_secret__",
                        application_id="__application_id__")
----
|===

* 手順3: 下記のファイルを開きパラメータを適切な値に変更します。
+
|===
|samples/demo_config.yaml
a|
----
demo_configuration:
   device_id: "__device_id__"
   get_model_device_id: "__get_model_device_id__"
   publish_model_wait_response_device_id: "__publish_model_wait_response_device_id__"
   model_id: "__model_id__"
   model: "__model__"
   converted: "__converted__"
   vendor_name: "__vendor_name__"
   comment: "__comment__"
   input_format_param: "__input_format_param__"
   network_config: "__network_config__"
   network_type: "__network_type__"
   metadata_format_id: "__metadata_format_id__"
   project_name: "__project_name__"
   model_platform: "__model_platform__"
   project_type: "__project_type__"
   latest_type: "__latest_type__"
   config_id: "__config_id__"
   sensor_loader_version_number: "__sensor_loader_version_number__"
   sensor_version_number: "__sensor_version_number__"
   model_version_number: "__model_version_number__"
   ap_fw_version_number: "__ap_fw_version_number__"
   device_ids: "__device_ids__"
   replace_model_id: "__replace_model_id__"
   timeout: "__timeout__"
   compiled_flg: "__compiled_flg__"
   app_name: "__app_name__"
   version_number: "__version_number__"
   file_name: "__file_name__"
   entry_point: "__entry_point__"
   schema_info: "__schema_info__"
   device_name: "__device_name__"
   connection_state: "__connection_state__"
   device_group_id: "__device_group_id__"
   scope: "__scope__"
   sub_directory_name: "__sub_directory_name__"
   number_of_images: "__number_of_images__"
   skip: "__skip__"
   order_by: "__order_by__"
   number_of_inference_results: "__number_of_inference_results__"
   filter: "__filter__"
   raw: "__raw__"
   time: "__time__"
----
|===

=== API import_device_app 実行

aotファイルの内容をBase64 Encodeして `**samples/device_app_file_content.txt**` に配置します。

=== アプリケーション開始

CLIデモを実行するにはrootフォルダからcmdターミナルを開き、次のコマンドを実行します。

```
    python samples/console_access_client_api_demo.py
```

NOTE: demo-consoleでAPIを一括実行した場合は、他のAPIの処理時間の影響により失敗することがあります。 +
その場合は失敗したAPIを個別で実行してください。
APIを個別で実行する場合は、samples/console_access_client_api_demo.pyを開き、実行しないAPIをコメントアウトしてください。

* 例：
|===
|samples/console_access_client_api_demo.py
a|
----
    # DeviceManagement - StartUploadInferenceResult
    # response = device_management_obj.start_upload_inference_result(device_id=device_id)
    # print("START UPLOAD INFERENCE RESULT:", response)
----
|===
