= Cloud SDK pass:[<br/>] Console Access Library pass:[<br/>] Python pass:[<br/>] Tutorial pass:[<br/>]
:sectnums:
:sectnumlevels: 1
:author: Copyright 2023 Sony Semiconductor Solutions Corporation
:version-label: Version 
:revnumber: x.x.x
:revdate: YYYY - MM - DD
:trademark-desc1: AITRIOS™ and AITRIOS logos are the registered trademarks or trademarks
:trademark-desc2: of Sony Group Corporation or its affiliated companies.
:toc:
:toc-title: TOC
:toclevels: 1
:chapter-label:
:lang: en

== Objective

To explain the various APIs exposed by "**Console Access Library**" and help the user to build and use the library.

== Prerequisites
- Python 3.8.10
- Python dependency modules

    * requests>=2.31.0
    * jsonschema>=4.6.2
    * setuptools>=65.5.1
    * wheel>=0.37.1
    * PyYAML>=6.0
    * marshmallow>=3.17.0
    * pytest>=7.1.2
    * pytest-html-reporter>=0.2.9
    * pytest-ordering>=0.6
    * sphinx==4.3.2
    * myst-parser>=0.18.0
    * sphinx-rtd-theme>=1.0.0
    * sphinxcontrib-napoleon>=0.7
    * rst2pdf>=0.99
    * streamlit==1.11.1
    * pytest-timeout>=2.1.0
    * PyJWT>=2.6.0
    * nassl>=4.0
    * cryptography>=36.0
    * validators>=0.18
    * msal>=1.22.0

=== "**Console Access Library**" API Specification
Please refer the below procedure regarding how to refer the "**Console Access Library**" API specifications. 

1. Clone the repository
    ** https://github.com/SonySemiconductorSolutions/aitrios-sdk-console-access-lib-python

2.  Open `**docs/api-reference/index.html**` available in the cloned directory via browser

== Usage

=== Installation

. Clone the repository

. Install Python dependencies for demo application
+
```
    pip install -r requirements.txt
```

. Run the following command to install into current Python environment
+
```
    python -m pip install lib/python_client.
```

. Run the following command to install into current Python environment
+
```
    python -m pip install src/.
```

. Network proxy setting
+
To use the "**Console Access Library**" in a proxy environment, set the `**https_proxy**` environment variable
+
```
    export https_proxy=http://username:password@proxyhost:port
```

<<<

=== Set configuration parameter to start "**Console Access Library**" sample application

==== Option 1: Using console access setting file

* Step 1: Create console access setting parameters with real values
+
`samples/console_access_settings.yaml`
+

|===
| In the case of using "**Console Developer Edition**"
a|
[source,Yaml]
----
    console_access_settings:
        console_endpoint: "__console_endpoint__"
        portal_authorization_endpoint: "__portal_authorization_endpoint__"
        client_secret: "__client_secret__"
        client_id: "__client_id__"
----
|===

+

|===
| In the case of using "**Console Enterprise Edition**"
a|
[source,Yaml]
----
    console_access_settings:
        console_endpoint: "__base_url__"
        portal_authorization_endpoint: "https://login.microsoftonline.com/'__tenant_id__'"
        client_id: "__client_id__"
        client_secret: "__creant_secret__"
        application_id: "__application_id__"
----
|===

* Step 2: Import modules `**ReadConsoleAccessSettings**`, `**Config**` and `**Client**` into "**Console Access Library**" sample application
+

|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    from console_access_library.common.read_console_access_settings import ReadConsoleAccessSettings
    from console_access_library.common.config import Config
    from console_access_library.client import Client
----
|===

* Step 3: Set path for console access setting file, and then instantiate "**Console Access Library**" `**ReadConsoleAccessSettings**` + 
To create `**console_access_settings.yaml file**`, please refer step 1
+

|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    SETTING_FILE_PATH = os.path.join(os.getcwd(), "samples", "console_access_settings.yaml")
    read_console_access_settings_obj = ReadConsoleAccessSettings(SETTING_FILE_PATH)
----
|===

* Step 4: Instantiate "**Console Access Library**" `**Config**`
+ 

|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    config_obj = Config(console_endpoint=read_console_access_settings_obj.console_endpoint,
                        portal_authorization_endpoint=read_console_access_settings_obj.portal_authorization_endpoint,
                        client_id=read_console_access_settings_obj.client_id,
                        client_secret=read_console_access_settings_obj.client_secret,
                        application_id=read_console_access_settings_obj.application_id)
----
|===

==== Option 2: Exporting the real values to environment without creating a console access setting file

* Step 1: Export the real values to environment
+
```
    export CONSOLE_ENDPOINT="__console_endpoint__"
    export PORTAL_AUTHORIZATION_ENDPOINT="__portal_authorization_endpoint__"
    export CLIENT_SECRET="__client_secret__"
    export CLIENT_ID="__client_id__"
    export APPLICATION_ID="__application_id__"
```
* Step 2: Import modules `**Config**` and `**Client**` into "**Console Access Library**" sample application
+

|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    from console_access_library.common.config import Config
    from console_access_library.client import Client
----
|===

* Step 3: Instantiate "**Console Access Library**" `**Config**` with real values
+

|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    config_obj = Config(console_endpoint=None,
                        portal_authorization_endpoint=None,
                        client_id=None,
                        client_secret=None,
                        application_id=None)
----
|===

<<<

==== Option 3: Passing real values to "**Console Access Library**" Config

* Step 1: Import modules `**Config**` and `**Client**` into "**Console Access Library**" sample application
+

|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    from console_access_library.common.config import Config
    from console_access_library.client import Client
----
|===

* Step 2: Instantiate "**Console Access Library**" `**Config**` with real values
+
|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    config_obj = Config(console_endpoint="__console_endpoint__", 
                        portal_authorization_endpoint="__portal_authorization_endpoint__",
                        client_id="__client_id__", 
                        client_secret="__client_secret__",
                        application_id="__application_id__")
----
|===

* 手順3: 下記のファイルを開きパラメータを適切な値に変更します。
+
|===
|samples/demo_config.yaml
a|
----
demo_configuration:
   device_id: "__device_id__"
   get_model_device_id: "__get_model_device_id__"
   publish_model_wait_response_device_id: "__publish_model_wait_response_device_id__"
   model_id: "__model_id__"
   model: "__model__"
   converted: "__converted__"
   vendor_name: "__vendor_name__"
   comment: "__comment__"
   input_format_param: "__input_format_param__"
   network_config: "__network_config__"
   network_type: "__network_type__"
   metadata_format_id: "__metadata_format_id__"
   project_name: "__project_name__"
   model_platform: "__model_platform__"
   project_type: "__project_type__"
   latest_type: "__latest_type__"
   config_id: "__config_id__"
   sensor_loader_version_number: "__sensor_loader_version_number__"
   sensor_version_number: "__sensor_version_number__"
   model_version_number: "__model_version_number__"
   ap_fw_version_number: "__ap_fw_version_number__"
   device_ids: "__device_ids__"
   replace_model_id: "__replace_model_id__"
   timeout: "__timeout__"
   compiled_flg: "__compiled_flg__"
   app_name: "__app_name__"
   version_number: "__version_number__"
   file_name: "__file_name__"
   entry_point: "__entry_point__"
   schema_info: "__schema_info__"
   device_name: "__device_name__"
   connection_state: "__connection_state__"
   device_group_id: "__device_group_id__"
   scope: "__scope__"
   sub_directory_name: "__sub_directory_name__"
   number_of_images: "__number_of_images__"
   skip: "__skip__"
   order_by: "__order_by__"
   number_of_inference_results: "__number_of_inference_results__"
   filter: "__filter__"
   raw: "__raw__"
   time: "__time__"
----
|===

=== To run API import_device_app

Place the contents of aot file as base64 in the `**samples/device_app_file_content.txt**`.

=== Starting the App

To run the CLI demo, open cmd terminal from the root folder, and run the following command.

```
    python samples/console_access_client_api_demo.py
```

NOTE: When APIs are batch-executed in demo-console, it may fail due to the impact of the processing time of 
other APIs. In such case, execute the failed APIs separately. +
When executing APIs individually, open samples/console_access_client_api_demo.py and 
comment out the APIs that are not to be executed.

* Example:

|===
|samples/console_access_client_api_demo.py
a|
[source,python]
----
    # DeviceManagement - StartUploadInferenceResult
    # response = device_management_obj.start_upload_inference_result(device_id=device_id)
    # print("START UPLOAD INFERENCE RESULT:", response)
----
|===
