# coding: utf-8

"""
    AITRIOS | Console

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from aitrios_console_rest_client_sdk_primitive import schemas  # noqa: F401


class Firmware(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            firmware_id = schemas.StrSchema
            firmware_type = schemas.StrSchema
            comment = schemas.StrSchema
            ins_id = schemas.StrSchema
            ins_date = schemas.StrSchema
            upd_id = schemas.StrSchema
            upd_date = schemas.StrSchema
            
            
            class versions(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    
                    class items(
                        schemas.DictSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            class properties:
                                file_name = schemas.StrSchema
                                version_number = schemas.StrSchema
                                ppl = schemas.StrSchema
                                stored_type = schemas.StrSchema
                                stored_uri = schemas.StrSchema
                                comment = schemas.StrSchema
                                ins_id = schemas.StrSchema
                                ins_date = schemas.StrSchema
                                upd_id = schemas.StrSchema
                                upd_date = schemas.StrSchema
                                __annotations__ = {
                                    "file_name": file_name,
                                    "version_number": version_number,
                                    "ppl": ppl,
                                    "stored_type": stored_type,
                                    "stored_uri": stored_uri,
                                    "comment": comment,
                                    "ins_id": ins_id,
                                    "ins_date": ins_date,
                                    "upd_id": upd_id,
                                    "upd_date": upd_date,
                                }
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["file_name"]) -> MetaOapg.properties.file_name: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["version_number"]) -> MetaOapg.properties.version_number: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["ppl"]) -> MetaOapg.properties.ppl: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["stored_type"]) -> MetaOapg.properties.stored_type: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["stored_uri"]) -> MetaOapg.properties.stored_uri: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["comment"]) -> MetaOapg.properties.comment: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["ins_id"]) -> MetaOapg.properties.ins_id: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["ins_date"]) -> MetaOapg.properties.ins_date: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["upd_id"]) -> MetaOapg.properties.upd_id: ...
                        
                        @typing.overload
                        def __getitem__(self, name: typing_extensions.Literal["upd_date"]) -> MetaOapg.properties.upd_date: ...
                        
                        @typing.overload
                        def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                        
                        def __getitem__(self, name: typing.Union[typing_extensions.Literal["file_name", "version_number", "ppl", "stored_type", "stored_uri", "comment", "ins_id", "ins_date", "upd_id", "upd_date", ], str]):
                            # dict_instance[name] accessor
                            return super().__getitem__(name)
                        
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["file_name"]) -> typing.Union[MetaOapg.properties.file_name, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["version_number"]) -> typing.Union[MetaOapg.properties.version_number, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["ppl"]) -> typing.Union[MetaOapg.properties.ppl, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["stored_type"]) -> typing.Union[MetaOapg.properties.stored_type, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["stored_uri"]) -> typing.Union[MetaOapg.properties.stored_uri, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["comment"]) -> typing.Union[MetaOapg.properties.comment, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["ins_id"]) -> typing.Union[MetaOapg.properties.ins_id, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["ins_date"]) -> typing.Union[MetaOapg.properties.ins_date, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["upd_id"]) -> typing.Union[MetaOapg.properties.upd_id, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: typing_extensions.Literal["upd_date"]) -> typing.Union[MetaOapg.properties.upd_date, schemas.Unset]: ...
                        
                        @typing.overload
                        def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                        
                        def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["file_name", "version_number", "ppl", "stored_type", "stored_uri", "comment", "ins_id", "ins_date", "upd_id", "upd_date", ], str]):
                            return super().get_item_oapg(name)
                        
                    
                        def __new__(
                            cls,
                            *args: typing.Union[dict, frozendict.frozendict, ],
                            file_name: typing.Union[MetaOapg.properties.file_name, str, schemas.Unset] = schemas.unset,
                            version_number: typing.Union[MetaOapg.properties.version_number, str, schemas.Unset] = schemas.unset,
                            ppl: typing.Union[MetaOapg.properties.ppl, str, schemas.Unset] = schemas.unset,
                            stored_type: typing.Union[MetaOapg.properties.stored_type, str, schemas.Unset] = schemas.unset,
                            stored_uri: typing.Union[MetaOapg.properties.stored_uri, str, schemas.Unset] = schemas.unset,
                            comment: typing.Union[MetaOapg.properties.comment, str, schemas.Unset] = schemas.unset,
                            ins_id: typing.Union[MetaOapg.properties.ins_id, str, schemas.Unset] = schemas.unset,
                            ins_date: typing.Union[MetaOapg.properties.ins_date, str, schemas.Unset] = schemas.unset,
                            upd_id: typing.Union[MetaOapg.properties.upd_id, str, schemas.Unset] = schemas.unset,
                            upd_date: typing.Union[MetaOapg.properties.upd_date, str, schemas.Unset] = schemas.unset,
                            _configuration: typing.Optional[schemas.Configuration] = None,
                            **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                        ) -> 'items':
                            return super().__new__(
                                cls,
                                *args,
                                file_name=file_name,
                                version_number=version_number,
                                ppl=ppl,
                                stored_type=stored_type,
                                stored_uri=stored_uri,
                                comment=comment,
                                ins_id=ins_id,
                                ins_date=ins_date,
                                upd_id=upd_id,
                                upd_date=upd_date,
                                _configuration=_configuration,
                                **kwargs,
                            )
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, dict, frozendict.frozendict, ]], typing.List[typing.Union[MetaOapg.items, dict, frozendict.frozendict, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'versions':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            __annotations__ = {
                "firmware_id": firmware_id,
                "firmware_type": firmware_type,
                "comment": comment,
                "ins_id": ins_id,
                "ins_date": ins_date,
                "upd_id": upd_id,
                "upd_date": upd_date,
                "versions": versions,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["firmware_id"]) -> MetaOapg.properties.firmware_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["firmware_type"]) -> MetaOapg.properties.firmware_type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["comment"]) -> MetaOapg.properties.comment: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ins_id"]) -> MetaOapg.properties.ins_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ins_date"]) -> MetaOapg.properties.ins_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["upd_id"]) -> MetaOapg.properties.upd_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["upd_date"]) -> MetaOapg.properties.upd_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["versions"]) -> MetaOapg.properties.versions: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["firmware_id", "firmware_type", "comment", "ins_id", "ins_date", "upd_id", "upd_date", "versions", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["firmware_id"]) -> typing.Union[MetaOapg.properties.firmware_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["firmware_type"]) -> typing.Union[MetaOapg.properties.firmware_type, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["comment"]) -> typing.Union[MetaOapg.properties.comment, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ins_id"]) -> typing.Union[MetaOapg.properties.ins_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ins_date"]) -> typing.Union[MetaOapg.properties.ins_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["upd_id"]) -> typing.Union[MetaOapg.properties.upd_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["upd_date"]) -> typing.Union[MetaOapg.properties.upd_date, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["versions"]) -> typing.Union[MetaOapg.properties.versions, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["firmware_id", "firmware_type", "comment", "ins_id", "ins_date", "upd_id", "upd_date", "versions", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        firmware_id: typing.Union[MetaOapg.properties.firmware_id, str, schemas.Unset] = schemas.unset,
        firmware_type: typing.Union[MetaOapg.properties.firmware_type, str, schemas.Unset] = schemas.unset,
        comment: typing.Union[MetaOapg.properties.comment, str, schemas.Unset] = schemas.unset,
        ins_id: typing.Union[MetaOapg.properties.ins_id, str, schemas.Unset] = schemas.unset,
        ins_date: typing.Union[MetaOapg.properties.ins_date, str, schemas.Unset] = schemas.unset,
        upd_id: typing.Union[MetaOapg.properties.upd_id, str, schemas.Unset] = schemas.unset,
        upd_date: typing.Union[MetaOapg.properties.upd_date, str, schemas.Unset] = schemas.unset,
        versions: typing.Union[MetaOapg.properties.versions, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Firmware':
        return super().__new__(
            cls,
            *args,
            firmware_id=firmware_id,
            firmware_type=firmware_type,
            comment=comment,
            ins_id=ins_id,
            ins_date=ins_date,
            upd_id=upd_id,
            upd_date=upd_date,
            versions=versions,
            _configuration=_configuration,
            **kwargs,
        )
