# coding: utf-8

"""
    AITRIOS | Console

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from aitrios_console_rest_client_sdk_primitive import schemas  # noqa: F401


class GetDeviceAppsResponseVersions(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "deploy_count",
            "ins_date",
            "upd_id",
            "upd_date",
            "compiled_flg",
            "comment",
            "ins_id",
            "version",
            "status",
        }
        
        class properties:
            version = schemas.StrSchema
            compiled_flg = schemas.StrSchema
            status = schemas.StrSchema
            comment = schemas.StrSchema
            deploy_count = schemas.StrSchema
            ins_id = schemas.StrSchema
            ins_date = schemas.StrSchema
            upd_id = schemas.StrSchema
            upd_date = schemas.StrSchema
            __annotations__ = {
                "version": version,
                "compiled_flg": compiled_flg,
                "status": status,
                "comment": comment,
                "deploy_count": deploy_count,
                "ins_id": ins_id,
                "ins_date": ins_date,
                "upd_id": upd_id,
                "upd_date": upd_date,
            }
    
    deploy_count: MetaOapg.properties.deploy_count
    ins_date: MetaOapg.properties.ins_date
    upd_id: MetaOapg.properties.upd_id
    upd_date: MetaOapg.properties.upd_date
    compiled_flg: MetaOapg.properties.compiled_flg
    comment: MetaOapg.properties.comment
    ins_id: MetaOapg.properties.ins_id
    version: MetaOapg.properties.version
    status: MetaOapg.properties.status
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["version"]) -> MetaOapg.properties.version: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["compiled_flg"]) -> MetaOapg.properties.compiled_flg: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["comment"]) -> MetaOapg.properties.comment: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deploy_count"]) -> MetaOapg.properties.deploy_count: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ins_id"]) -> MetaOapg.properties.ins_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ins_date"]) -> MetaOapg.properties.ins_date: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["upd_id"]) -> MetaOapg.properties.upd_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["upd_date"]) -> MetaOapg.properties.upd_date: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["version", "compiled_flg", "status", "comment", "deploy_count", "ins_id", "ins_date", "upd_id", "upd_date", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["version"]) -> MetaOapg.properties.version: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["compiled_flg"]) -> MetaOapg.properties.compiled_flg: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["status"]) -> MetaOapg.properties.status: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["comment"]) -> MetaOapg.properties.comment: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deploy_count"]) -> MetaOapg.properties.deploy_count: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ins_id"]) -> MetaOapg.properties.ins_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ins_date"]) -> MetaOapg.properties.ins_date: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["upd_id"]) -> MetaOapg.properties.upd_id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["upd_date"]) -> MetaOapg.properties.upd_date: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["version", "compiled_flg", "status", "comment", "deploy_count", "ins_id", "ins_date", "upd_id", "upd_date", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        deploy_count: typing.Union[MetaOapg.properties.deploy_count, str, ],
        ins_date: typing.Union[MetaOapg.properties.ins_date, str, ],
        upd_id: typing.Union[MetaOapg.properties.upd_id, str, ],
        upd_date: typing.Union[MetaOapg.properties.upd_date, str, ],
        compiled_flg: typing.Union[MetaOapg.properties.compiled_flg, str, ],
        comment: typing.Union[MetaOapg.properties.comment, str, ],
        ins_id: typing.Union[MetaOapg.properties.ins_id, str, ],
        version: typing.Union[MetaOapg.properties.version, str, ],
        status: typing.Union[MetaOapg.properties.status, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'GetDeviceAppsResponseVersions':
        return super().__new__(
            cls,
            *args,
            deploy_count=deploy_count,
            ins_date=ins_date,
            upd_id=upd_id,
            upd_date=upd_date,
            compiled_flg=compiled_flg,
            comment=comment,
            ins_id=ins_id,
            version=version,
            status=status,
            _configuration=_configuration,
            **kwargs,
        )
