# coding: utf-8

"""
    Console API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Generated by: https://openapi-generator.tech
"""

from aitrios_console_rest_client_sdk_primitive.paths.deployconfigurations.post import CreateDeployConfiguration
from aitrios_console_rest_client_sdk_primitive.paths.deployconfigurations_config_id.delete import DeleteDeployConfiguration
from aitrios_console_rest_client_sdk_primitive.paths.deployconfigurations_config_id.put import DeployByConfiguration
from aitrios_console_rest_client_sdk_primitive.paths.devices_device_id_deploys_deploy_id.put import DeployDeviceCancel
from aitrios_console_rest_client_sdk_primitive.paths.deployconfigurations.get import GetDeployConfigurations
from aitrios_console_rest_client_sdk_primitive.paths.devices_device_id_deploys.get import GetDeployHistory


class DeployApi(
    CreateDeployConfiguration,
    DeleteDeployConfiguration,
    DeployByConfiguration,
    DeployDeviceCancel,
    GetDeployConfigurations,
    GetDeployHistory,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
