demo_configuration:
  device_id: "__device_id__"
  get_model_device_id: "__get_model_device_id__"
  publish_model_wait_response_device_id: "__publish_model_wait_response_device_id__"
  model_id: "__model_id__"
  model: "__model__"
  converted: "__converted__"
  vendor_name: "__vendor_name__"
  comment: "__comment__"
  input_format_param: "__input_format_param__"
  network_config: "__network_config__"
  network_type: "__network_type__"
  metadata_format_id: "__metadata_format_id__"
  project_name: "__project_name__"
  model_platform: "__model_platform__"
  project_type: "__project_type__"
  latest_type: "__latest_type__"
  config_id: "__config_id__"
  sensor_loader_version_number: "__sensor_loader_version_number__"
  sensor_version_number: "__sensor_version_number__"
  model_version_number: "__model_version_number__"
  ap_fw_version_number: "__ap_fw_version_number__"
  device_ids: "__device_ids__"
  replace_model_id: "__replace_model_id__"
  timeout: "__timeout__"
  compiled_flg: "__compiled_flg__"
  app_name: "__app_name__"
  version_number: "__version_number__"
  file_name: "__file_name__"
  entry_point: "__entry_point__"
  schema_info: "__schema_info__"
  device_name: "__device_name__"
  connection_state: "__connection_state__"
  device_group_id: "__device_group_id__"
  scope: "__scope__"
  sub_directory_name: "__sub_directory_name__"
  number_of_images: "__number_of_images__"
  skip: "__skip__"
  order_by: "__order_by__"
  number_of_inference_results: "__number_of_inference_results__"
  filter: "__filter__"
  raw: "__raw__"
  time: "__time__"