demo_configuration:
  device_id: "__device_id__"
  model_id: "__model_id__"
  model: "__model__"
  config_id: "__config_id__"
  app_name: "__app_name__"
  file_content_name: "__file_content_name__"
  version_number: "__version_number__"
  sub_directory_name: "__sub_directory_name__"