# coding: utf-8

"""
    AITRIOS | Console

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.4.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.import_images_from_scblob_json_body import ImportImagesFromScblobJsonBody
from aitrios_console_rest_client_sdk_primitive import configuration


class TestImportImagesFromScblobJsonBody(unittest.TestCase):
    """ImportImagesFromScblobJsonBody unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
