# coding: utf-8

"""
    AITRIOS | Console

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.train_model_import_images_from_blob_folder_data_importimagesfromblobfolderindto_json_body import TrainModelImportImagesFromBlobFolderDataImportimagesfromblobfolderindtoJsonBody
from aitrios_console_rest_client_sdk_primitive import configuration


class TestTrainModelImportImagesFromBlobFolderDataImportimagesfromblobfolderindtoJsonBody(unittest.TestCase):
    """TrainModelImportImagesFromBlobFolderDataImportimagesfromblobfolderindtoJsonBody unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
