# coding: utf-8

"""
    AITRIOS | Console

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.cancel_parameter_camera_file_json_body import CancelParameterCameraFileJsonBody
from aitrios_console_rest_client_sdk_primitive import configuration


class TestCancelParameterCameraFileJsonBody(unittest.TestCase):
    """CancelParameterCameraFileJsonBody unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
