# coding: utf-8

"""
    AITRIOS | Console

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.train_model_create_project_image_regions_data_createprojectimageregionsindto_json_body import TrainModelCreateProjectImageRegionsDataCreateprojectimageregionsindtoJsonBody
from aitrios_console_rest_client_sdk_primitive import configuration


class TestTrainModelCreateProjectImageRegionsDataCreateprojectimageregionsindtoJsonBody(unittest.TestCase):
    """TrainModelCreateProjectImageRegionsDataCreateprojectimageregionsindtoJsonBody unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
