# coding: utf-8

"""
    AITRIOS | Console

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.get_device_apps_response_versions import GetDeviceAppsResponseVersions
from aitrios_console_rest_client_sdk_primitive import configuration


class TestGetDeviceAppsResponseVersions(unittest.TestCase):
    """GetDeviceAppsResponseVersions unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
