"""
    Console API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.train_model_update_project_image_regions_data_updateprojectimageregionsindto_json_body import TrainModelUpdateProjectImageRegionsDataUpdateprojectimageregionsindtoJsonBody


class TestTrainModelUpdateProjectImageRegionsDataUpdateprojectimageregionsindtoJsonBody(unittest.TestCase):
    """TrainModelUpdateProjectImageRegionsDataUpdateprojectimageregionsindtoJsonBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrainModelUpdateProjectImageRegionsDataUpdateprojectimageregionsindtoJsonBody(self):
        """Test TrainModelUpdateProjectImageRegionsDataUpdateprojectimageregionsindtoJsonBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrainModelUpdateProjectImageRegionsDataUpdateprojectimageregionsindtoJsonBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
