"""
    Console API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.train_model_update_base_model_version_data_updatebasemodelversionindto_json_body import TrainModelUpdateBaseModelVersionDataUpdatebasemodelversionindtoJsonBody


class TestTrainModelUpdateBaseModelVersionDataUpdatebasemodelversionindtoJsonBody(unittest.TestCase):
    """TrainModelUpdateBaseModelVersionDataUpdatebasemodelversionindtoJsonBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrainModelUpdateBaseModelVersionDataUpdatebasemodelversionindtoJsonBody(self):
        """Test TrainModelUpdateBaseModelVersionDataUpdatebasemodelversionindtoJsonBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrainModelUpdateBaseModelVersionDataUpdatebasemodelversionindtoJsonBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
