"""
    Console API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.get_inferenceresults200_response_inner_inferences_inner1 import GetInferenceresults200ResponseInnerInferencesInner1


class TestGetInferenceresults200ResponseInnerInferencesInner1(unittest.TestCase):
    """GetInferenceresults200ResponseInnerInferencesInner1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetInferenceresults200ResponseInnerInferencesInner1(self):
        """Test GetInferenceresults200ResponseInnerInferencesInner1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetInferenceresults200ResponseInnerInferencesInner1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
