"""
    Console API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.get_images200_response_images_inner import GetImages200ResponseImagesInner


class TestGetImages200ResponseImagesInner(unittest.TestCase):
    """GetImages200ResponseImagesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetImages200ResponseImagesInner(self):
        """Test GetImages200ResponseImagesInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetImages200ResponseImagesInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
