"""
    Console API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.train_model_import_images_from_scblob_data_importimagesfromscblobindto_json_body import TrainModelImportImagesFromScblobDataImportimagesfromscblobindtoJsonBody


class TestTrainModelImportImagesFromScblobDataImportimagesfromscblobindtoJsonBody(unittest.TestCase):
    """TrainModelImportImagesFromScblobDataImportimagesfromscblobindtoJsonBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrainModelImportImagesFromScblobDataImportimagesfromscblobindtoJsonBody(self):
        """Test TrainModelImportImagesFromScblobDataImportimagesfromscblobindtoJsonBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrainModelImportImagesFromScblobDataImportimagesfromscblobindtoJsonBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
