"""
    Console API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.get_images200_response_images_inner import GetImages200ResponseImagesInner
from aitrios_console_rest_client_sdk_primitive.model.int import Int
globals()['GetImages200ResponseImagesInner'] = GetImages200ResponseImagesInner
globals()['Int'] = Int
from aitrios_console_rest_client_sdk_primitive.model.get_images200_response import GetImages200Response


class TestGetImages200Response(unittest.TestCase):
    """GetImages200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetImages200Response(self):
        """Test GetImages200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetImages200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
