"""
    Console API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.camera_setting_file_import_camera_configuration_file_data_importcameraconfigurationfileindto_json_body import CameraSettingFileImportCameraConfigurationFileDataImportcameraconfigurationfileindtoJsonBody


class TestCameraSettingFileImportCameraConfigurationFileDataImportcameraconfigurationfileindtoJsonBody(unittest.TestCase):
    """CameraSettingFileImportCameraConfigurationFileDataImportcameraconfigurationfileindtoJsonBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCameraSettingFileImportCameraConfigurationFileDataImportcameraconfigurationfileindtoJsonBody(self):
        """Test CameraSettingFileImportCameraConfigurationFileDataImportcameraconfigurationfileindtoJsonBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CameraSettingFileImportCameraConfigurationFileDataImportcameraconfigurationfileindtoJsonBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
