"""
    Console API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.export_images200_response import ExportImages200Response


class TestExportImages200Response(unittest.TestCase):
    """ExportImages200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExportImages200Response(self):
        """Test ExportImages200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ExportImages200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
