"""
    Console API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0.2
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aitrios_console_rest_client_sdk_primitive
from aitrios_console_rest_client_sdk_primitive.model.get_image_directories200_response_inner_devices_inner import GetImageDirectories200ResponseInnerDevicesInner


class TestGetImageDirectories200ResponseInnerDevicesInner(unittest.TestCase):
    """GetImageDirectories200ResponseInnerDevicesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetImageDirectories200ResponseInnerDevicesInner(self):
        """Test GetImageDirectories200ResponseInnerDevicesInner"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetImageDirectories200ResponseInnerDevicesInner()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
